#!/usr/bin/python3

import gi
gi.require_version('Gtk', '3.0')
import sys

# import modules.notification

def main():
    if len(sys.argv) <= 1:
        raise SystemExit('Mode not specified')

    mode = sys.argv[1]
    
    if mode == 'bar':
        import modules.bar
        modules.bar.Main()
    elif mode == 'dashboard':
        import modules.dashboard
        modules.dashboard.Main()
    elif mode == 'search':
        import modules.search
        execute = len(sys.argv) > 2 and sys.argv[2] == 'execute_shell'
        modules.search.Main(execute)
    # elif mode == "notification":
    #    modules.notification.Main()
    elif mode == 'powermenu':
        import modules.powermenu
        modules.powermenu.Main()
    elif mode == "screenflash":
        import modules.screenflash
        modules.screenflash.Main()
    else:
        raise SystemExit('Unknown mode')

try:
    (lambda: __name__ == '__main__' and main())()
except KeyboardInterrupt:
    pass
